[package]
name = "rusty_sword_arena"
version = "1.0.1"
authors = ["Nathan Stocks <cleancut@github.com>"]
description = "Library/repository for the half-day Rust tutorial teaching you how to make a game client in Rust."
documentation = "https://agileperception.com/doc/rusty_sword_arena/"
homepage = "https://conferences.oreilly.com/oscon/oscon-or/public/schedule/detail/67116"
repository = "https://github.com/CleanCut/rusty_sword_arena"
readme = "README.md"
keywords = ["tutorial", "rusty", "sword", "arena", "learn"]
license = "MIT"
edition = "2018"

[dependencies]
# For graphics support ðŸ‘¾ (OpenGL) -- maybe try gfx-rs (Vulkan) instead in the future?
glium = "0.21"

# For raw networking -- need to switch to something that deals better with disconnects in the future, maybe nanomsg?
zmq = "0.8"

# The following three are all so we can send Rust values over the network
# ----
# The core serde APIs, including the Serialize and Deserialize traits.
serde = { version = "1.0", features = ["derive"] }

# The format we want to serialize to/from.
bincode = "1.0"

# For random numbers! ðŸŽ²
rand = "0.5"

# For playing sound ðŸ”Š - to have the _same_ sound overlap, we'll need to either hack on impose or use "rodio" directly
impose = "0.2.0"